"""Initial tables

Revision ID: c2e1e2abbd32
Revises: 
Create Date: 2025-02-04 12:34:09.525190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2e1e2abbd32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chancecommands',
    sa.Column('type', sa.Enum('chance', 'chest', 'tax', name='chance_command_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('property_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiles',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('property', 'railway', 'company', 'special', name='tile_type_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('mortgage', sa.Float(), nullable=False),
    sa.Column('rent_1', sa.Float(), nullable=False),
    sa.Column('rent_2', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tile_id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('games_lost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('mortgage', sa.Float(), nullable=False),
    sa.Column('house_price', sa.Float(), nullable=False),
    sa.Column('hotel_price', sa.Float(), nullable=False),
    sa.Column('rent_0_house', sa.Float(), nullable=False),
    sa.Column('rent_1_house', sa.Float(), nullable=False),
    sa.Column('rent_2_house', sa.Float(), nullable=False),
    sa.Column('rent_3_house', sa.Float(), nullable=False),
    sa.Column('rent_4_house', sa.Float(), nullable=False),
    sa.Column('rent_hotel', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('railways',
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('mortgage', sa.Float(), nullable=False),
    sa.Column('rent_1', sa.Float(), nullable=False),
    sa.Column('rent_2', sa.Float(), nullable=False),
    sa.Column('rent_3', sa.Float(), nullable=False),
    sa.Column('rent_4', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tile_id')
    )
    op.create_table('specials',
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('go', 'chest', 'chance', 'tax', 'jail', 'casino', 'goto_jail', name='special_type_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tile_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specials')
    op.drop_table('railways')
    op.drop_table('properties')
    op.drop_table('players')
    op.drop_table('companies')
    op.drop_table('users')
    op.drop_table('tiles')
    op.drop_table('groups')
    op.drop_table('chancecommands')
    # ### end Alembic commands ###
